### PR TITLE
fix top section ui 

### LINKED ISSUE #32: fix top section ui (effort 3)
text is hardly visible, Login, password etc
Move eberything to the right 

image

image

add some space
image

when we are logging in instead of 
'Login' button add loading circle like it was before....

image

This is not part of th login... (remove it from here....) - this will be probably removed by Jakub
image

image

### PR DESCRIPTION
**Pull request by ibednorz**
Screenshot 2021-03-25 at 22 05 27
Screenshot 2021-03-25 at 22 05 37

### CODE REVIEW

**Review by pdybowski — CHANGES_REQUESTED** [review]
look at the ticket description:
image


yyyy....
image


register button doesnt do anything.. we have page for register

File: src/components/TopSection.jsx [hunk 1]
```diff
@@ -2,11 +2,11 @@ import React, { useMemo, useState } from 'react'
 import { COOKIE_TOKEN } from '../constants'
 import { getUserInfo, removeCookie } from '../utils'
 import { Login } from './Login'
-import Container from '@material-ui/core/Container'
 import Grid from '@material-ui/core/Grid'
 import Button from '@material-ui/core/Button'
 import { isUserLoggedIn } from '../utils'
 import '../content/css/topSection.css'
+import { HOTEL_OWNER_ROLE } from '../constants'
```
Comment (pdybowski) [inline src/components/TopSection.jsx]: we already import constants here

File: src/components/TopSection.jsx [hunk 2]
```diff
@@ -2,11 +2,11 @@ import React, { useMemo, useState } from 'react'
 import { COOKIE_TOKEN } from '../constants'
 import { getUserInfo, removeCookie } from '../utils'
 import { Login } from './Login'
-import Container from '@material-ui/core/Container'
 import Grid from '@material-ui/core/Grid'
 import Button from '@material-ui/core/Button'
 import { isUserLoggedIn } from '../utils'
```
Comment (pdybowski) [inline src/components/TopSection.jsx]: we already import ..utils

**Review by pdybowski — CHANGES_REQUESTED** [review]
... and code fixes
